USE ROLE ACCOUNTADMIN;


CREATE OR REPLACE WAREHOUSE EMERGENCY_ANALYTICS_WH
    WAREHOUSE_SIZE = 'X-SMALL'
    AUTO_SUSPEND = 60
    AUTO_RESUME = TRUE;


CREATE OR REPLACE DATABASE EMERGENCY_ANALYTICS;


CREATE OR REPLACE SCHEMA EMERGENCY_ANALYTICS.RAW;
CREATE OR REPLACE SCHEMA EMERGENCY_ANALYTICS.TRANSFORMED;
CREATE OR REPLACE SCHEMA EMERGENCY_ANALYTICS.ANALYTICS;


USE WAREHOUSE EMERGENCY_ANALYTICS_WH;
USE DATABASE EMERGENCY_ANALYTICS;
USE SCHEMA RAW;


SELECT
    CURRENT_DATABASE(),
    CURRENT_SCHEMA(),
    CURRENT_WAREHOUSE(),
    CURRENT_ROLE();